export const Configurations = {
  title: "ETD Admin",
  numberPerPage: 15,
  storageDBName: "storage-management-system",
  storageItemCollectionName: "storage_management_item",
  storageUserCollectionName: "storage_management_owner",
  drawerSize: 60,
  maximumNotSeenDuration: 300,
  defaultExpireDuration: 365,
  defaultWebhookUser: "dockerhub",
  defaultPaginationStartingPage: 1,
  defaultThrottleDuration: 1000,
  mongodbVersion: "4.4.10",
  appbarHeight: 60,
  defaultPadding: 30,
  defaultSleepDuration: 100,
  defaultRefreshInterval: 3000,
  defaultMessagePanelWidth: 400,
};
